### ISSUE TITLE
role for managing rooms

### ISSUE THREAD

**Issue by famedly-bot** [famedly/ansible-collection-matrix#18]
In GitLab by @jcgruenhage on Aug 23, 2021, 10:36

Our modules already offer a good low level API for managing matrix rooms, but we're lacking a higher level abstraction that takes in a bunch of variables and manages the rooms in an idempotent way.

### Desired features
 - [ ] creating a bunch of rooms and spaces in one run
 - [x] access control (public, invite only, knocking, restricted based on space membership)
 - [ ] idempotently upgrading rooms (to allow for the former) -> needs changes to our matrix_room module, because that should be handling the upgrade IMO
 - [ ] manage space hierarchy
 - [x] set encryption
 - [ ] \<your suggestions here\>

**Comment by jcgruenhage** [comment]
Closing because the role exists. If people are missing features, they should open issues for those instead.
